name: Python package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable caching for pip
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Verify imports
      run: |
        python -c "import sys; print(f'\nPython {sys.version}')"
        if [ -f requirements.txt ]; then python -c \"import pkgutil; [print(f'✅ {mod.name}') for mod in pkgutil.iter_modules()]\"; fi
    
    - name: Lint with flake8
      run: |
        # Basic syntax and undefined variables check (will fail)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # Style warnings only (won't fail)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run tests with pytest
      run: |
        pytest -v --cov=./ --cov-report=xml  # Basic test run with coverage
      env:
        PYTHONWARNINGS: "ignore"  # Suppress warnings
        
    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
